insert into pizza (name, price, created_at, updated_at) values ('Pizza Margherita', 1040, CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP());
insert into pizza (name, price, created_at, updated_at) values ('Proschiuto Cotto', 1340, CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP());
insert into pizza (name, price, created_at, updated_at) values ('Pizza Funghi', 1140, CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP());
insert into pizza (name, price, created_at, updated_at) values ('Pizza Broccoli', 1290, CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP());
insert into pizza (name, price, created_at, updated_at) values ('Pizza con Salsiccia Affumicate', 1290, CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP());
insert into pizza (name, price, created_at, updated_at) values ('Pizza Salame', 1340, CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP());
insert into pizza (name, price, created_at, updated_at) values ('Pizza con Peccorino Fresca', 1340, CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP());
insert into pizza (name, price, created_at, updated_at) values ('Ungherese', 1490, CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP());
insert into pizza (name, price, created_at, updated_at) values ('Gorgonzola e Spinacci ', 1490, CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP());
insert into pizza (name, price, created_at, updated_at) values ('Pizza Salsicca picante ', 1440, CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP());
insert into pizza (name, price, created_at, updated_at) values ('Pizza con Verdura', 1340, CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP());
insert into pizza (name, price, created_at, updated_at) values ('Pizza Napoletano', 1340, CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP());
insert into pizza (name, price, created_at, updated_at) values ('Pizza con Speck', 1440, CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP());
insert into pizza (name, price, created_at, updated_at) values ('Pizza di Tonno', 1490, CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP());
insert into pizza (name, price, created_at, updated_at) values ('Pizza Quattro Formaggio', 1490, CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP());
insert into pizza (name, price, created_at, updated_at) values ('Pizza Padrino', 1490, CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP());
insert into pizza (name, price, created_at, updated_at) values ('Pizza Gamberetti', 1490, CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP());
insert into pizza (name, price, created_at, updated_at) values ('Pizza Pepperoni', 1490, CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP());
insert into pizza (name, price, created_at, updated_at) values ('Pizza Spinacci', 1490, CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP());
insert into pizza (name, price, created_at, updated_at) values ('Quattro Stagioni', 1490, CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP());
insert into pizza (name, price, created_at, updated_at) values ('Pizza di Parma', 1990, CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP());
insert into pizza (name, price, created_at, updated_at) values ('Pizza Parmesan', 1290, CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP());
insert into pizza (name, price, created_at, updated_at) values ('Crema di Formaggio', 1290, CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP());
insert into pizza (name, price, created_at, updated_at) values ('Pizza Chili', 1490, CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP());
insert into pizza (name, price, created_at, updated_at) values ('Pizza Zucchini', 1390, CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP());
insert into pizza (name, price, created_at, updated_at) values ('Pizza al Salmone', 2190, CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP());
insert into pizza (name, price, created_at, updated_at) values ('Cipolla e Fagioli', 1490, CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP());


insert into topping (name, created_at, updated_at) values ('hamozott paradicsom', CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP());
insert into topping (name, created_at, updated_at) values ('tejszines-narancsos chili szosz', CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP());
insert into topping (name, created_at, updated_at) values ('tejszines-kapros alap', CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP());
insert into topping (name, created_at, updated_at) values ('csipos alap', CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP());
insert into topping (name, created_at, updated_at) values ('mozarella', CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP());
insert into topping (name, created_at, updated_at) values ('oregano', CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP());
insert into topping (name, created_at, updated_at) values ('bazsalikom', CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP());
insert into topping (name, created_at, updated_at) values ('pragai sonka', CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP());
insert into topping (name, created_at, updated_at) values ('gomba', CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP());
insert into topping (name, created_at, updated_at) values ('petrezselyem', CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP());
insert into topping (name, created_at, updated_at) values ('parasztkolbasz', CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP());
insert into topping (name, created_at, updated_at) values ('brokkoli', CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP());
insert into topping (name, created_at, updated_at) values ('lilahagyma', CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP());
insert into topping (name, created_at, updated_at) values ('fustolt parasztkolbasz', CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP());
insert into topping (name, created_at, updated_at) values ('szalami', CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP());
insert into topping (name, created_at, updated_at) values ('juhturo', CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP());
insert into topping (name, created_at, updated_at) values ('friss paradicsom', CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP());
insert into topping (name, created_at, updated_at) values ('olivabogyo', CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP());
insert into topping (name, created_at, updated_at) values ('fustult kolbasz', CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP());
insert into topping (name, created_at, updated_at) values ('fott sonka', CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP());
insert into topping (name, created_at, updated_at) values ('leveles spenot', CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP());
insert into topping (name, created_at, updated_at) values ('gorgonzola', CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP());
insert into topping (name, created_at, updated_at) values ('fokhagyma', CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP());
insert into topping (name, created_at, updated_at) values ('csipos olasz szalami', CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP());
insert into topping (name, created_at, updated_at) values ('grillezett cukkini', CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP());
insert into topping (name, created_at, updated_at) values ('padlizsan', CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP());
insert into topping (name, created_at, updated_at) values ('kaliforniai paprika', CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP());
insert into topping (name, created_at, updated_at) values ('hagyma', CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP());
insert into topping (name, created_at, updated_at) values ('kapribogyo', CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP());
insert into topping (name, created_at, updated_at) values ('szardinia', CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP());
insert into topping (name, created_at, updated_at) values ('speck (tiroli erlelt sonka)', CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP());
insert into topping (name, created_at, updated_at) values ('tonhaltorzs', CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP());
insert into topping (name, created_at, updated_at) values ('kakukkfu', CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP());
insert into topping (name, created_at, updated_at) values ('parmesan', CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP());
insert into topping (name, created_at, updated_at) values ('juhsajt', CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP());
insert into topping (name, created_at, updated_at) values ('garnelarak', CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP());
insert into topping (name, created_at, updated_at) values ('rukkola', CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP());
insert into topping (name, created_at, updated_at) values ('pepperoni', CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP());
insert into topping (name, created_at, updated_at) values ('spenot level', CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP());
insert into topping (name, created_at, updated_at) values ('tojas', CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP());
insert into topping (name, created_at, updated_at) values ('articsoka', CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP());
insert into topping (name, created_at, updated_at) values ('hazi kremsajt', CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP());
insert into topping (name, created_at, updated_at) values ('fustolt sajt', CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP());
insert into topping (name, created_at, updated_at) values ('cukkini', CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP());
insert into topping (name, created_at, updated_at) values ('kremsajt', CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP());
insert into topping (name, created_at, updated_at) values ('lazacfile', CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP());
insert into topping (name, created_at, updated_at) values ('szaritott paradicsom', CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP());
insert into topping (name, created_at, updated_at) values ('vorosbab', CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP());
insert into topping (name, created_at, updated_at) values ('parmai sonka', CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP());


insert into user (username, password, address, phone_number, e_mail, role) values ('user1', 'password1', 'address1', 'phone_number1', 'e_mail1', 'ADMIN');
insert into user (username, password, address, phone_number, e_mail, role) values ('user2', 'password2', 'address2', 'phone_number2', 'e_mail2', 'USER');
insert into user (username, password, address, phone_number, e_mail, role) values ('user3', 'password3', 'address3', 'phone_number3', 'e_mail3', 'USER');
insert into user (username, password, address, phone_number, e_mail, role) values ('user4', 'password4', 'address4', 'phone_number4', 'e_mail4', 'USER');


insert into orders (user_id, delivered, comment, created_at, updated_at) values (2, true, 'az 5-osre nem kerek lilahagymat', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
insert into orders (user_id, delivered, comment, created_at, updated_at) values (3, true, 'a 26-ost kapribogyo nelkul kerem', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
insert into orders (user_id, delivered, created_at, updated_at) values (2, false, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
insert into orders (user_id, delivered, created_at, updated_at) values (3, false, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
insert into orders (user_id, delivered, created_at, updated_at) values (4, false, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
insert into orders (user_id, delivered, created_at, updated_at) values (2, true, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());


insert into ordered_pizza (orders_id, pizzas_id) values (1, 5);
insert into ordered_pizza (orders_id, pizzas_id) values (1, 19);
insert into ordered_pizza (orders_id, pizzas_id) values (2, 1);
insert into ordered_pizza (orders_id, pizzas_id) values (2, 26);
insert into ordered_pizza (orders_id, pizzas_id) values (2, 16);
insert into ordered_pizza (orders_id, pizzas_id) values (3, 11);
insert into ordered_pizza (orders_id, pizzas_id) values (4, 20);
insert into ordered_pizza (orders_id, pizzas_id) values (4, 21);
insert into ordered_pizza (orders_id, pizzas_id) values (4, 22);
insert into ordered_pizza (orders_id, pizzas_id) values (5, 8);
insert into ordered_pizza (orders_id, pizzas_id) values (6, 3);
insert into ordered_pizza (orders_id, pizzas_id) values (6, 4);
insert into ordered_pizza (orders_id, pizzas_id) values (6, 15);
insert into ordered_pizza (orders_id, pizzas_id) values (6, 16);
insert into ordered_pizza (orders_id, pizzas_id) values (6, 20);


insert into favourite_pizza (users_id, pizzas_id) values (1, 4);
insert into favourite_pizza (users_id, pizzas_id) values (2, 8);
insert into favourite_pizza (users_id, pizzas_id) values (3, 9);
insert into favourite_pizza (users_id, pizzas_id) values (4, 15);


insert into pizza_topping (pizzas_id, toppings_id) values (1, 1);
insert into pizza_topping (pizzas_id, toppings_id) values (1, 5);
insert into pizza_topping (pizzas_id, toppings_id) values (1, 6);
insert into pizza_topping (pizzas_id, toppings_id) values (1, 7);
insert into pizza_topping (pizzas_id, toppings_id) values (2, 1);
insert into pizza_topping (pizzas_id, toppings_id) values (2, 5);
insert into pizza_topping (pizzas_id, toppings_id) values (2, 8);
insert into pizza_topping (pizzas_id, toppings_id) values (3, 1);
insert into pizza_topping (pizzas_id, toppings_id) values (3, 5);
insert into pizza_topping (pizzas_id, toppings_id) values (3, 9);
insert into pizza_topping (pizzas_id, toppings_id) values (3, 10);
insert into pizza_topping (pizzas_id, toppings_id) values (4, 1);
insert into pizza_topping (pizzas_id, toppings_id) values (4, 5);
insert into pizza_topping (pizzas_id, toppings_id) values (4, 11);
insert into pizza_topping (pizzas_id, toppings_id) values (4, 12);
insert into pizza_topping (pizzas_id, toppings_id) values (5, 1);
insert into pizza_topping (pizzas_id, toppings_id) values (5, 5);
insert into pizza_topping (pizzas_id, toppings_id) values (5, 13);
insert into pizza_topping (pizzas_id, toppings_id) values (5, 14);
insert into pizza_topping (pizzas_id, toppings_id) values (6, 1);
insert into pizza_topping (pizzas_id, toppings_id) values (6, 5);
insert into pizza_topping (pizzas_id, toppings_id) values (6, 15);
insert into pizza_topping (pizzas_id, toppings_id) values (6, 7);
insert into pizza_topping (pizzas_id, toppings_id) values (7, 1);
insert into pizza_topping (pizzas_id, toppings_id) values (7, 5);
insert into pizza_topping (pizzas_id, toppings_id) values (7, 16);
insert into pizza_topping (pizzas_id, toppings_id) values (7, 17);
insert into pizza_topping (pizzas_id, toppings_id) values (7, 18);
insert into pizza_topping (pizzas_id, toppings_id) values (8, 1);
insert into pizza_topping (pizzas_id, toppings_id) values (8, 13);
insert into pizza_topping (pizzas_id, toppings_id) values (8, 19);
insert into pizza_topping (pizzas_id, toppings_id) values (8, 15);
insert into pizza_topping (pizzas_id, toppings_id) values (8, 20);
insert into pizza_topping (pizzas_id, toppings_id) values (8, 5);
insert into pizza_topping (pizzas_id, toppings_id) values (9, 1);
insert into pizza_topping (pizzas_id, toppings_id) values (9, 5);
insert into pizza_topping (pizzas_id, toppings_id) values (9, 21);
insert into pizza_topping (pizzas_id, toppings_id) values (9, 13);
insert into pizza_topping (pizzas_id, toppings_id) values (9, 22);
insert into pizza_topping (pizzas_id, toppings_id) values (9, 23);
insert into pizza_topping (pizzas_id, toppings_id) values (10, 1);
insert into pizza_topping (pizzas_id, toppings_id) values (10, 5);
insert into pizza_topping (pizzas_id, toppings_id) values (10, 24);
insert into pizza_topping (pizzas_id, toppings_id) values (10, 7);
insert into pizza_topping (pizzas_id, toppings_id) values (11, 1);
insert into pizza_topping (pizzas_id, toppings_id) values (11, 25);
insert into pizza_topping (pizzas_id, toppings_id) values (11, 26);
insert into pizza_topping (pizzas_id, toppings_id) values (11, 9);
insert into pizza_topping (pizzas_id, toppings_id) values (11, 27);
insert into pizza_topping (pizzas_id, toppings_id) values (11, 10);
insert into pizza_topping (pizzas_id, toppings_id) values (11, 23);
insert into pizza_topping (pizzas_id, toppings_id) values (11, 28);
insert into pizza_topping (pizzas_id, toppings_id) values (11, 5);
insert into pizza_topping (pizzas_id, toppings_id) values (12, 1);
insert into pizza_topping (pizzas_id, toppings_id) values (12, 13);
insert into pizza_topping (pizzas_id, toppings_id) values (12, 6);
insert into pizza_topping (pizzas_id, toppings_id) values (12, 29);
insert into pizza_topping (pizzas_id, toppings_id) values (12, 18);
insert into pizza_topping (pizzas_id, toppings_id) values (12, 30);
insert into pizza_topping (pizzas_id, toppings_id) values (13, 1);
insert into pizza_topping (pizzas_id, toppings_id) values (13, 5);
insert into pizza_topping (pizzas_id, toppings_id) values (13, 31);
insert into pizza_topping (pizzas_id, toppings_id) values (13, 7);
insert into pizza_topping (pizzas_id, toppings_id) values (14, 1);
insert into pizza_topping (pizzas_id, toppings_id) values (14, 32);
insert into pizza_topping (pizzas_id, toppings_id) values (14, 13);
insert into pizza_topping (pizzas_id, toppings_id) values (14, 33);
insert into pizza_topping (pizzas_id, toppings_id) values (14, 18);
insert into pizza_topping (pizzas_id, toppings_id) values (14, 5);
insert into pizza_topping (pizzas_id, toppings_id) values (15, 1);
insert into pizza_topping (pizzas_id, toppings_id) values (15, 5);
insert into pizza_topping (pizzas_id, toppings_id) values (15, 22);
insert into pizza_topping (pizzas_id, toppings_id) values (15, 34);
insert into pizza_topping (pizzas_id, toppings_id) values (15, 35);
insert into pizza_topping (pizzas_id, toppings_id) values (16, 1);
insert into pizza_topping (pizzas_id, toppings_id) values (16, 13);
insert into pizza_topping (pizzas_id, toppings_id) values (16, 31);
insert into pizza_topping (pizzas_id, toppings_id) values (16, 18);
insert into pizza_topping (pizzas_id, toppings_id) values (16, 35);
insert into pizza_topping (pizzas_id, toppings_id) values (17, 1);
insert into pizza_topping (pizzas_id, toppings_id) values (17, 36);
insert into pizza_topping (pizzas_id, toppings_id) values (17, 18);
insert into pizza_topping (pizzas_id, toppings_id) values (17, 37);
insert into pizza_topping (pizzas_id, toppings_id) values (17, 23);
insert into pizza_topping (pizzas_id, toppings_id) values (18, 1);
insert into pizza_topping (pizzas_id, toppings_id) values (18, 5);
insert into pizza_topping (pizzas_id, toppings_id) values (18, 9);
insert into pizza_topping (pizzas_id, toppings_id) values (18, 31);
insert into pizza_topping (pizzas_id, toppings_id) values (18, 38);
insert into pizza_topping (pizzas_id, toppings_id) values (18, 10);
insert into pizza_topping (pizzas_id, toppings_id) values (19, 1);
insert into pizza_topping (pizzas_id, toppings_id) values (19, 5);
insert into pizza_topping (pizzas_id, toppings_id) values (19, 39);
insert into pizza_topping (pizzas_id, toppings_id) values (19, 31);
insert into pizza_topping (pizzas_id, toppings_id) values (19, 23);
insert into pizza_topping (pizzas_id, toppings_id) values (19, 40);
insert into pizza_topping (pizzas_id, toppings_id) values (20, 1);
insert into pizza_topping (pizzas_id, toppings_id) values (20, 5);
insert into pizza_topping (pizzas_id, toppings_id) values (20, 31);
insert into pizza_topping (pizzas_id, toppings_id) values (20, 9);
insert into pizza_topping (pizzas_id, toppings_id) values (20, 41);
insert into pizza_topping (pizzas_id, toppings_id) values (20, 17);
insert into pizza_topping (pizzas_id, toppings_id) values (20, 18);
insert into pizza_topping (pizzas_id, toppings_id) values (21, 1);
insert into pizza_topping (pizzas_id, toppings_id) values (21, 5);
insert into pizza_topping (pizzas_id, toppings_id) values (21, 49);
insert into pizza_topping (pizzas_id, toppings_id) values (21, 37);
insert into pizza_topping (pizzas_id, toppings_id) values (22, 1);
insert into pizza_topping (pizzas_id, toppings_id) values (22, 5);
insert into pizza_topping (pizzas_id, toppings_id) values (22, 34);
insert into pizza_topping (pizzas_id, toppings_id) values (22, 17);
insert into pizza_topping (pizzas_id, toppings_id) values (23, 1);
insert into pizza_topping (pizzas_id, toppings_id) values (23, 5);
insert into pizza_topping (pizzas_id, toppings_id) values (23, 42);
insert into pizza_topping (pizzas_id, toppings_id) values (23, 18);
insert into pizza_topping (pizzas_id, toppings_id) values (24, 2);
insert into pizza_topping (pizzas_id, toppings_id) values (24, 5);
insert into pizza_topping (pizzas_id, toppings_id) values (24, 20);
insert into pizza_topping (pizzas_id, toppings_id) values (24, 43);
insert into pizza_topping (pizzas_id, toppings_id) values (25, 1);
insert into pizza_topping (pizzas_id, toppings_id) values (25, 5);
insert into pizza_topping (pizzas_id, toppings_id) values (25, 44);
insert into pizza_topping (pizzas_id, toppings_id) values (25, 39);
insert into pizza_topping (pizzas_id, toppings_id) values (25, 45);
insert into pizza_topping (pizzas_id, toppings_id) values (26, 3);
insert into pizza_topping (pizzas_id, toppings_id) values (26, 46);
insert into pizza_topping (pizzas_id, toppings_id) values (26, 47);
insert into pizza_topping (pizzas_id, toppings_id) values (26, 5);
insert into pizza_topping (pizzas_id, toppings_id) values (26, 29);
insert into pizza_topping (pizzas_id, toppings_id) values (26, 13);
insert into pizza_topping (pizzas_id, toppings_id) values (27, 4);
insert into pizza_topping (pizzas_id, toppings_id) values (27, 1);
insert into pizza_topping (pizzas_id, toppings_id) values (27, 14);
insert into pizza_topping (pizzas_id, toppings_id) values (27, 13);
insert into pizza_topping (pizzas_id, toppings_id) values (27, 48);
insert into pizza_topping (pizzas_id, toppings_id) values (27, 23);


